### ISSUE TITLE
Not compatible with latest Quartz (2.3.1)

### ISSUE THREAD

**Issue by rbirkby** [dtinteractive/Ninject.Extensions.Quartz#5]
Quartz 2.3.1 uses Common.Logging 3.0
Common.Logging 3.0 is backward incompatible with Common.Logging 2.x

Additionally, Ninject.Extensions.Quartz makes calls to Common.Logging directly, but doesn't declare the dependency in the nuspec. If a dependency in the nuspec with an upper bound of <3.0 was specified, this would have prevented nuget from upgrading Quartz and Common.Logging

    2015-01-16 15:43:35,893 [9] ERROR Topshelf.Hosts.ConsoleRunHost - An exception occurred System.TypeInitializationException: The type initializer for 'Ninject.Extensions.Quartz.NinjectJobFactory' threw an exception. ---> System.MissingMethodException: Method not found: 'Common.Logging.ILog Common.Logging.LogManager.GetLogger(System.Type)'.
       at Ninject.Extensions.Quartz.NinjectJobFactory..cctor()
       --- End of inner exception stack trace ---
      at Ninject.Extensions.Quartz.NinjectJobFactory..ctor(IKernel kernel)
      at DynamicInjector864dfe2094ee485d916d21d981f0c530(Object[] )
      at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
      at Ninject.Activation.Context.ResolveInternal(Object scope)
      at Ninject.Activation.Context.Resolve()
      at Ninject.KernelBase.<>c__DisplayClass15.<Resolve>b__f(IBinding binding)

**Comment by peaklor** [comment]
I took latest source and updated with the latest nuget packages for Common.Logging and Quartz to resolve the issue.

**Comment by remcoros** [comment]
Litterally the only place where logging is used in this library is here: https://github.com/dtinteractive/Ninject.Extensions.Quartz/blob/master/Source/Ninject.Extensions.Quartz/NinjectJobFactory.cs#L52

Also, Common.Logging is not in the .nuspec file.

Because of this, I suggest to completely remove Common.Logging and that single log statement from this library.

I will create a PR for this.

**Comment by crmckenzie** [comment]
When do you think you will publish the new nuget package?

**Comment by markhuber** [comment]
I've been working on another project I'm trying to release. I'll look into when I can put some time towards this project.

**Comment by mgilcrease** [comment]
A more interesting question is, why am I getting these emails? :-D

**Comment by markhuber** [comment]
You're not in the organization anymore, you must have this project watched in github, this is one of the public projects @mgilcrease You will probably have to remove the watch yourself.

**Comment by scott-xu** [comment]
Hi @markhuber Can you please help do this update? Or if you grant me permission, I can do the merge and update the nuget package. Thanks!

**Comment by efij** [comment]
i really need that nuget fix, when do you think you can publish it on visual studio ?

**Comment by gautejohan** [comment]
Anyone have a solution for this problem?

**Comment by remcoros** [comment]
@gautejohan Copy/paste in your own solution. It's just three files and MIT licensed
